# Generated by Django 2.2 on 2020-09-03 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20200902_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='syllabus',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
