# Generated by Django 2.2 on 2020-09-28 07:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('registered_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('email', models.EmailField(db_index=True, max_length=250, unique=True)),
                ('username', models.CharField(max_length=250)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_student', models.BooleanField(default=False)),
                ('is_merchant', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('line1', models.CharField(max_length=250)),
                ('city', models.CharField(blank=True, max_length=250, null=True)),
                ('apartment', models.CharField(blank=True, max_length=250, null=True)),
                ('building', models.CharField(blank=True, max_length=250, null=True)),
                ('landmark', models.CharField(blank=True, max_length=250, null=True)),
                ('district', models.CharField(default=None, max_length=250)),
                ('state', models.CharField(default=None, max_length=250)),
                ('pincode', models.CharField(default=None, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=250, verbose_name='course_batch_name')),
                ('start_time', models.CharField(default=None, max_length=20)),
                ('end_time', models.CharField(default=None, max_length=20)),
                ('student_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('students_enrolled', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=250, verbose_name='coaching_branch_name')),
                ('branch_type', models.CharField(choices=[('Main', 'Main'), ('Sub', 'Sub')], default='Main', max_length=250, verbose_name='coaching_branch')),
            ],
        ),
        migrations.CreateModel(
            name='Coaching',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=250, unique=True)),
                ('description', models.TextField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('logo_link', models.URLField()),
                ('merchant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('review', models.CharField(default=None, max_length=200)),
                ('rating', models.IntegerField(default=None)),
                ('review_time', models.DateTimeField()),
                ('coaching', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mania.Coaching')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mania.Batch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(default=None, max_length=100)),
                ('description', models.CharField(default=None, max_length=200)),
                ('coaching', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mania.Coaching')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('message', models.CharField(default=None, max_length=200)),
                ('timestamp', models.DateTimeField()),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='msg_receiver', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='msg_sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Merchant_Details',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('organization', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('mobile', models.CharField(max_length=250)),
                ('stream', models.CharField(choices=[('Science', 'Science'), ('Commerce', 'Commerce'), ('Arts', 'Arts'), ('Music', 'Music'), ('Dance', 'Dance'), ('Sports', 'Sports')], default=None, max_length=250, verbose_name='coaching_stream')),
                ('merchant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Geolocation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('lat', models.DecimalField(decimal_places=2, default=None, max_digits=10)),
                ('lng', models.DecimalField(decimal_places=2, default=None, max_digits=10)),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location_of', to='mania.Address')),
            ],
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('disc_code', models.CharField(default=None, max_length=20)),
                ('description', models.CharField(default=None, max_length=200)),
                ('disc_percent', models.IntegerField(default=None)),
                ('coaching', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mania.Coaching')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=250, verbose_name='branch_course_name')),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('syllabus', models.FileField(blank=True, null=True, upload_to='')),
                ('fees', models.DecimalField(decimal_places=2, default=None, max_digits=10)),
                ('currency', models.CharField(blank=True, default='INR', max_length=30)),
                ('is_active', models.BooleanField(default=False)),
                ('stream', models.CharField(choices=[('Science', 'Science'), ('Commerce', 'Commerce'), ('Arts', 'Arts'), ('Music', 'Music'), ('Dance', 'Dance'), ('Sports', 'Sports')], default=None, max_length=250, verbose_name='coaching_stream')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses_of', to='mania.Branch')),
            ],
        ),
        migrations.CreateModel(
            name='CoachingReview',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('rating', models.PositiveIntegerField()),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('coaching', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_of', to='mania.Coaching')),
            ],
        ),
        migrations.CreateModel(
            name='CoachingMetaData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('contact', models.CharField(default=None, max_length=20)),
                ('help_contact', models.CharField(blank=True, default=None, max_length=20)),
                ('owner_name', models.CharField(blank=True, max_length=250, null=True)),
                ('owner_description', models.TextField(blank=True, null=True)),
                ('owner_image', models.ImageField(blank=True, null=True, upload_to='owners/')),
                ('owner_image_link', models.URLField(blank=True, default=None, null=True)),
                ('established_on', models.DateField()),
                ('coaching', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metadata_of', to='mania.Coaching')),
            ],
        ),
        migrations.CreateModel(
            name='CoachingFacultyMember',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=250)),
                ('age', models.PositiveIntegerField()),
                ('specialization', models.CharField(max_length=250)),
                ('meta_description', models.TextField(blank=True, null=True)),
                ('faculty_image', models.ImageField(blank=True, null=True, upload_to='faculties/')),
                ('faculty_image_link', models.URLField()),
                ('coaching', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_of', to='mania.Coaching')),
            ],
        ),
        migrations.AddField(
            model_name='branch',
            name='coaching',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='mania.Coaching'),
        ),
        migrations.AddField(
            model_name='batch',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches_of', to='mania.Course'),
        ),
        migrations.AddField(
            model_name='batch',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaches', to='mania.CoachingFacultyMember'),
        ),
        migrations.CreateModel(
            name='BankAccountDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('account_no', models.CharField(default=None, max_length=30)),
                ('ifsc_code', models.CharField(default=None, max_length=20)),
                ('bank_name', models.CharField(default=None, max_length=50)),
                ('account_holder', models.CharField(default=None, max_length=100)),
                ('adhar_card', models.FileField(blank=True, null=True, upload_to='adhar_cards/')),
                ('pan_card', models.FileField(blank=True, null=True, upload_to='pan_cards/')),
                ('mobile_no', models.CharField(default=None, max_length=20)),
                ('coaching', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mania.Coaching')),
            ],
        ),
        migrations.AddField(
            model_name='address',
            name='branch',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address_of', to='mania.Branch'),
        ),
    ]
