# Generated by Django 2.2 on 2020-09-08 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mania', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='stream',
            field=models.CharField(choices=[('Science', 'Science'), ('Commerce', 'Commerce'), ('Arts', 'Arts'), ('Music', 'Music'), ('Dance', 'Dance'), ('Sports', 'Sports')], default=None, max_length=250, verbose_name='coaching_stream'),
        ),
        migrations.CreateModel(
            name='Merchant_Details',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('external_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('organization', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('mobile', models.CharField(max_length=250)),
                ('stream', models.CharField(choices=[('Science', 'Science'), ('Commerce', 'Commerce'), ('Arts', 'Arts'), ('Music', 'Music'), ('Dance', 'Dance'), ('Sports', 'Sports')], default=None, max_length=250, verbose_name='coaching_stream')),
                ('merchant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
